### ISSUE TITLE
`@sourceloop/core`: The `rateLimitAction` is not getting route context

### ISSUE THREAD

**Issue by shubhamp-sf** [sourcefuse/loopback4-microservice-catalog#1600]
**Describe the bug**

The change introduced by https://github.com/sourcefuse/loopback4-microservice-catalog/commit/9c42a9b9d59db38dc4db580a53294643ed6f3f7f moved the ratelimit action before the findRoute is getting called. Resulting in unbound values for `CoreBindings.CONTROLLER_CLASS` and `CoreBindings.CONTROLLER_METHOD_NAME` in the metadata provider of ratelimiter extension.

This causes ineffectiveness of any overridden config values on route level.
Eg.

```ts
  @ratelimit(false)
  @get('/ping')
  @response(200, PING_RESPONSE)
  ping(): string {
      return "pong".
  }
``` 
Here disabling the ratelimit won't work as it doesn't get the correct controller and method name.

Related: https://github.com/loopbackio/loopback-next/issues/1144
